import { Antonio, Inter, Roboto } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Header } from '@/components/header/header';
import TracingBlob from '@/components/ui/tracing-blob';
import '@/styles/globals.css';
import '@/styles/mdx.css';

const antonio = Antonio({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-antonio'
});

const roboto = Roboto({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
	weight: ['300', '400', '500', '700']
});

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter'
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className={cn(antonio.variable, roboto.variable, inter.variable, 'bg-slate-900 font-inter antialiased')}
		>
			<body>
				<Header />
				{children}
				<TracingBlob />
				<div className="fixed inset-0 backdrop-blur-[7px] -z-10"></div>
			</body>
		</html>
	);
}
