import { Antonio, Roboto } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Header } from '@/components/header/header';
import '@/styles/globals.css';

const antonio = Antonio({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-antonio'
});

const roboto = Roboto({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
	weight: ['300', '400', '500', '700']
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={cn(antonio.variable, roboto.variable, 'bg-black text-white font-roboto')}>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
